@ECHO OFF
@COLOR 1F

SET FLOPPY_IMAGE=./floppy
SET OUTPUT_FILE=B:\KERNEL.BIN
SET LD_SCRIPT=LINK.LD
SET GCC_OPTIONS=-Wall -std=gnu99 -nostdinc -I./include -c -o

:START
	CLS
	GOTO MENU
	
:MENU
	ECHO -------------------------MY OS MENU-------------------------
	ECHO ------------------------------------------------------------
	ECHO 1.    BUILD LIBRARY
	ECHO 2.    BUILD DRIVERS HARDWARE
	ECHO 3.    BUILD DRIVERS SYSTEM
	ECHO 4.    BUILD KERNEL
	ECHO 5.    SAVE IMAGE
	ECHO 6.    RUN BOCHS
	ECHO 7.    BUILD ALL + SAVE + RUN KERNEL
	ECHO 8.    OPEN IMAGE
	ECHO 9.    CLOSE IMAGE
	ECHO 0.    EXIT
	ECHO ------------------------------------------------------------
	SET INPUT=
	SET /P INPUT=ACTION:
	IF /I '%INPUT%'=='1' (
		@ECHO MATH.C
		gcc %GCC_OPTIONS% ./OBJ/MATH.O ./LIBSRC/MATH.c
		@ECHO STDIO.C
		gcc %GCC_OPTIONS% ./OBJ/STDIO.O ./LIBSRC/STDIO.c
		@ECHO STRING.C
		gcc %GCC_OPTIONS% ./OBJ/STRING.O ./LIBSRC/STRING.c
		@ECHO lib.a
		ar rvs ./LIB/lib.a ./OBJ/STDIO.O ./OBJ/MATH.O ./OBJ/STRING.O
	)
	IF /I '%INPUT%'=='2' (
		@ECHO BIOS.C
		gcc %GCC_OPTIONS% ./OBJ/BIOS.O ./DRIVERSRC/HARDWARE/BIOS.c
		@ECHO CMOS.C
		gcc %GCC_OPTIONS% ./OBJ/CMOS.O ./DRIVERSRC/HARDWARE/CMOS.c
		@ECHO DMA.C
		gcc %GCC_OPTIONS% ./OBJ/DMA.O ./DRIVERSRC/HARDWARE/DMA.c
		@ECHO FDC.C
		gcc %GCC_OPTIONS% ./OBJ/FDC.O ./DRIVERSRC/HARDWARE/FDC.c
		@ECHO IDE.C
		gcc %GCC_OPTIONS% ./OBJ/IDE.O ./DRIVERSRC/HARDWARE/IDE.c
		@ECHO LPT.C
		gcc %GCC_OPTIONS% ./OBJ/LPT.O ./DRIVERSRC/HARDWARE/LPT.c
		@ECHO PCI.C
		gcc %GCC_OPTIONS% ./OBJ/PCI.O ./DRIVERSRC/HARDWARE/PCI.c
		@ECHO RS232.C
		gcc %GCC_OPTIONS% ./OBJ/RS232.O ./DRIVERSRC/HARDWARE/RS232.c
		@ECHO TIMER.C
		gcc %GCC_OPTIONS% ./OBJ/TIMER.O ./DRIVERSRC/HARDWARE/TIMER.c
		@ECHO 8042.C
		gcc %GCC_OPTIONS% ./OBJ/8042.O ./DRIVERSRC/HARDWARE/8042/8042.c
		@ECHO KEYBOARD.C
		gcc %GCC_OPTIONS% ./OBJ/KEYBOARD.O ./DRIVERSRC/HARDWARE/8042/KEYBOARD.c
		@ECHO MOUSE.C
		gcc %GCC_OPTIONS% ./OBJ/MOUSE.O ./DRIVERSRC/HARDWARE/8042/MOUSE.c
		@ECHO hw.a
		ar rvs ./DRIVER/hw.a ./OBJ/BIOS.O ./OBJ/CMOS.O ./OBJ/DMA.O ./OBJ/FDC.O ./OBJ/IDE.O ./OBJ/LPT.O
		ar rvs ./DRIVER/hw.a ./OBJ/PCI.O ./OBJ/RS232.O ./OBJ/TIMER.O ./OBJ/8042.O ./OBJ/KEYBOARD.O
		ar rvs ./DRIVER/hw.a ./OBJ/MOUSE.O
	)
	IF /I '%INPUT%'=='3' (
		@ECHO 8259.C
		gcc %GCC_OPTIONS% ./OBJ/8259.O ./DRIVERSRC/SYSTEM/CPU/8259.c
		@ECHO GDT.C
		gcc %GCC_OPTIONS% ./OBJ/GDT.O ./DRIVERSRC/SYSTEM/CPU/GDT.c
		@ECHO IDT.C
		gcc %GCC_OPTIONS% ./OBJ/IDT.O ./DRIVERSRC/SYSTEM/CPU/IDT.c
		@ECHO INT.C
		gcc %GCC_OPTIONS% ./OBJ/INT.O ./DRIVERSRC/SYSTEM/CPU/INT.c
		@ECHO IRQ.C
		gcc %GCC_OPTIONS% ./OBJ/IRQ.O ./DRIVERSRC/SYSTEM/CPU/IRQ.c
		@ECHO ISR.C
		gcc %GCC_OPTIONS% ./OBJ/ISR.O ./DRIVERSRC/SYSTEM/CPU/ISR.c
		@ECHO TSS.C
		gcc %GCC_OPTIONS% ./OBJ/TSS.O ./DRIVERSRC/SYSTEM/CPU/TSS.c
		@ECHO FAT12.C
		gcc %GCC_OPTIONS% ./OBJ/FAT12.O ./DRIVERSRC/SYSTEM/FS/FAT12.c
		@ECHO VFS.C
		gcc %GCC_OPTIONS% ./OBJ/VFS.O ./DRIVERSRC/SYSTEM/FS/VFS.c
		@ECHO PAGEDIR.C
		gcc %GCC_OPTIONS% ./OBJ/PAGEDIR.O ./DRIVERSRC/SYSTEM/MEM/PAGEDIR.c
		@ECHO PAGEFAULT.C
		gcc %GCC_OPTIONS% ./OBJ/PAGEFAULT.O ./DRIVERSRC/SYSTEM/MEM/PAGEFAULT.c
		@ECHO PAGETABLE.C
		gcc %GCC_OPTIONS% ./OBJ/PAGETABLE.O ./DRIVERSRC/SYSTEM/MEM/PAGETABLE.c
		@ECHO PHYSICAL.C
		gcc %GCC_OPTIONS% ./OBJ/PHYSICAL.O ./DRIVERSRC/SYSTEM/MEM/PHYSICAL.c
		@ECHO VIRTUAL.C
		gcc %GCC_OPTIONS% ./OBJ/VIRTUAL.O ./DRIVERSRC/SYSTEM/MEM/VIRTUAL.c
		@ECHO sys.a
		ar rvs ./DRIVER/sys.a ./OBJ/8259.O ./OBJ/GDT.O ./OBJ/INT.O ./OBJ/IDT.O ./OBJ/IRQ.O ./OBJ/ISR.O ./OBJ/TSS.O
		ar rvs ./DRIVER/sys.a ./OBJ/FAT12.O ./OBJ/VFS.O ./OBJ/PAGEDIR.O ./OBJ/PAGEFAULT.O ./OBJ/PAGETABLE.O
		ar rvs ./DRIVER/sys.a ./OBJ/PHYSICAL.O ./OBJ/VIRTUAL.O
	)
	IF /I '%INPUT%'=='4' (
		@ECHO START.ASM
		nasm -f aout ./KERNELSRC/START.ASM -o ./OBJ/START.O
		@ECHO MAIN.C
		gcc %GCC_OPTIONS% ./OBJ/MAIN.O ./KERNELSRC/MAIN.c
		@ECHO COMMAND.C
		gcc %GCC_OPTIONS% ./OBJ/COMMAND.O ./KERNELSRC/COMMAND.c
		@ECHO LINKING KERNEL.BIN
		LD -T %LD_SCRIPT% -o %OUTPUT_FILE% ./OBJ/START.O ./OBJ/MAIN.O ./OBJ/COMMAND.O ./LIB/lib.a ./DRIVER/sys.a ./DRIVER/hw.a
	)
	IF /I '%INPUT%'=='5' (
		VFD SAVE
	)
	IF /I '%INPUT%'=='6' (
		BOCHS
	)
	IF /I '%INPUT%'=='7' (
		@ECHO MATH.C
		gcc %GCC_OPTIONS% ./OBJ/MATH.O ./LIBSRC/MATH.c
		@ECHO STDIO.C
		gcc %GCC_OPTIONS% ./OBJ/STDIO.O ./LIBSRC/STDIO.c
		@ECHO STRING.C
		gcc %GCC_OPTIONS% ./OBJ/STRING.O ./LIBSRC/STRING.c
		@ECHO lib.a
		ar rvs ./LIB/lib.a ./OBJ/STDIO.O ./OBJ/MATH.O ./OBJ/STRING.O
		@ECHO BIOS.C
		gcc %GCC_OPTIONS% ./OBJ/BIOS.O ./DRIVERSRC/HARDWARE/BIOS.c
		@ECHO CMOS.C
		gcc %GCC_OPTIONS% ./OBJ/CMOS.O ./DRIVERSRC/HARDWARE/CMOS.c
		@ECHO DMA.C
		gcc %GCC_OPTIONS% ./OBJ/DMA.O ./DRIVERSRC/HARDWARE/DMA.c
		@ECHO FDC.C
		gcc %GCC_OPTIONS% ./OBJ/FDC.O ./DRIVERSRC/HARDWARE/FDC.c
		@ECHO IDE.C
		gcc %GCC_OPTIONS% ./OBJ/IDE.O ./DRIVERSRC/HARDWARE/IDE.c
		@ECHO LPT.C
		gcc %GCC_OPTIONS% ./OBJ/LPT.O ./DRIVERSRC/HARDWARE/LPT.c
		@ECHO PCI.C
		gcc %GCC_OPTIONS% ./OBJ/PCI.O ./DRIVERSRC/HARDWARE/PCI.c
		@ECHO RS232.C
		gcc %GCC_OPTIONS% ./OBJ/RS232.O ./DRIVERSRC/HARDWARE/RS232.c
		@ECHO TIMER.C
		gcc %GCC_OPTIONS% ./OBJ/TIMER.O ./DRIVERSRC/HARDWARE/TIMER.c
		@ECHO 8042.C
		gcc %GCC_OPTIONS% ./OBJ/8042.O ./DRIVERSRC/HARDWARE/8042/8042.c
		@ECHO KEYBOARD.C
		gcc %GCC_OPTIONS% ./OBJ/KEYBOARD.O ./DRIVERSRC/HARDWARE/8042/KEYBOARD.c
		@ECHO MOUSE.C
		gcc %GCC_OPTIONS% ./OBJ/MOUSE.O ./DRIVERSRC/HARDWARE/8042/MOUSE.c
		@ECHO hw.a
		ar rvs ./DRIVER/hw.a ./OBJ/BIOS.O ./OBJ/CMOS.O ./OBJ/DMA.O ./OBJ/FDC.O ./OBJ/IDE.O ./OBJ/LPT.O
		ar rvs ./DRIVER/hw.a ./OBJ/PCI.O ./OBJ/RS232.O ./OBJ/TIMER.O ./OBJ/8042.O ./OBJ/KEYBOARD.O
		ar rvs ./DRIVER/hw.a ./OBJ/MOUSE.O
		@ECHO 8259.C
		gcc %GCC_OPTIONS% ./OBJ/8259.O ./DRIVERSRC/SYSTEM/CPU/8259.c
		@ECHO GDT.C
		gcc %GCC_OPTIONS% ./OBJ/GDT.O ./DRIVERSRC/SYSTEM/CPU/GDT.c
		@ECHO IDT.C
		gcc %GCC_OPTIONS% ./OBJ/IDT.O ./DRIVERSRC/SYSTEM/CPU/IDT.c
		@ECHO INT.C
		gcc %GCC_OPTIONS% ./OBJ/INT.O ./DRIVERSRC/SYSTEM/CPU/INT.c
		@ECHO IRQ.C
		gcc %GCC_OPTIONS% ./OBJ/IRQ.O ./DRIVERSRC/SYSTEM/CPU/IRQ.c
		@ECHO ISR.C
		gcc %GCC_OPTIONS% ./OBJ/ISR.O ./DRIVERSRC/SYSTEM/CPU/ISR.c
		@ECHO TSS.C
		gcc %GCC_OPTIONS% ./OBJ/TSS.O ./DRIVERSRC/SYSTEM/CPU/TSS.c
		@ECHO FAT12.C
		gcc %GCC_OPTIONS% ./OBJ/FAT12.O ./DRIVERSRC/SYSTEM/FS/FAT12.c
		@ECHO VFS.C
		gcc %GCC_OPTIONS% ./OBJ/VFS.O ./DRIVERSRC/SYSTEM/FS/VFS.c
		@ECHO PAGEDIR.C
		gcc %GCC_OPTIONS% ./OBJ/PAGEDIR.O ./DRIVERSRC/SYSTEM/MEM/PAGEDIR.c
		@ECHO PAGEFAULT.C
		gcc %GCC_OPTIONS% ./OBJ/PAGEFAULT.O ./DRIVERSRC/SYSTEM/MEM/PAGEFAULT.c
		@ECHO PAGETABLE.C
		gcc %GCC_OPTIONS% ./OBJ/PAGETABLE.O ./DRIVERSRC/SYSTEM/MEM/PAGETABLE.c
		@ECHO PHYSICAL.C
		gcc %GCC_OPTIONS% ./OBJ/PHYSICAL.O ./DRIVERSRC/SYSTEM/MEM/PHYSICAL.c
		@ECHO VIRTUAL.C
		gcc %GCC_OPTIONS% ./OBJ/VIRTUAL.O ./DRIVERSRC/SYSTEM/MEM/VIRTUAL.c
		@ECHO sys.a
		ar rvs ./DRIVER/sys.a ./OBJ/8259.O ./OBJ/GDT.O ./OBJ/INT.O ./OBJ/IDT.O ./OBJ/IRQ.O ./OBJ/ISR.O ./OBJ/TSS.O
		ar rvs ./DRIVER/sys.a ./OBJ/FAT12.O ./OBJ/VFS.O ./OBJ/PAGEDIR.O ./OBJ/PAGEFAULT.O ./OBJ/PAGETABLE.O
		ar rvs ./DRIVER/sys.a ./OBJ/PHYSICAL.O ./OBJ/VIRTUAL.O
		@ECHO START.ASM
		nasm -f aout ./KERNELSRC/START.ASM -o ./OBJ/START.O
		@ECHO MAIN.C
		gcc %GCC_OPTIONS% ./OBJ/MAIN.O ./KERNELSRC/MAIN.c
		@ECHO COMMAND.C
		gcc %GCC_OPTIONS% ./OBJ/COMMAND.O ./KERNELSRC/COMMAND.c
		@ECHO LINKING KERNEL.BIN
		LD -T %LD_SCRIPT% -o %OUTPUT_FILE% ./OBJ/START.O ./OBJ/MAIN.O ./OBJ/COMMAND.O ./LIB/lib.a ./DRIVER/sys.a ./DRIVER/hw.a
		VFD SAVE
		BOCHS
	)
	IF /I '%INPUT%'=='8' (
	    VFD INSTALL
		VFD START
		VFD OPEN %FLOPPY_IMAGE% /RAM /W /144
	)
	IF /I '%INPUT%'=='9' (
	    VFD CLOSE
		VFD STOP
		VFD REMOVE
	)
	IF /I '%INPUT%'=='0' EXIT /B
	PAUSE
	GOTO START
